[channels]
# discord channel webhook
test = "https://discord.com/api/webhooks/1234/abcd"

[messages]
test = "Testing 1..2..3.. :smile:"

[mentions]
# optional groups to prepend the message
all = "@everyone"
role = "<@&123456>"

[presets]
# quick messages with fixed combinations
test = { channel = "test", message = "test", mention = "" }
